using System.Text.RegularExpressions;
using Avalonia.Platform;
using NutManager.Core.Models;

namespace NutManager.Agent.Config.Localization;

/// <summary>What a line of the terms is, which is all the styling needs to know.</summary>
public enum AgentTermsBlockKind
{
    /// <summary>The document title, once, at the top.</summary>
    Title,

    /// <summary>A numbered section heading.</summary>
    Heading,

    /// <summary>Ordinary prose.</summary>
    Paragraph,

    /// <summary>An item in a list.</summary>
    Bullet,
}

/// <summary>One rendered line. Immutable, because the document never changes while it is on screen.</summary>
public sealed record AgentTermsBlock(AgentTermsBlockKind Kind, string Text);

/// <summary>
/// The product's terms of use, read from the canonical documents rather than restated.
///
/// docs/TERMS-OF-USE.md is the source and docs/TERMS-OF-USE.en-US.md is its translation; both are
/// linked into this assembly as resources. Nothing here paraphrases, shortens or adapts them: a
/// second wording of the terms living in a view model is a second set of terms, and the one the
/// operator reads would then depend on which screen they opened.
///
/// The same two files back the RTF the installers show, generated by scripts/build-terms-rtf.ps1.
/// The parsing rules below are that script's rules, so the text accepted at install time and the text
/// shown here cannot present the same document differently.
/// </summary>
public static class AgentTermsDocument
{
    private const string PortugueseAsset = "avares://NutManager.Agent.Config/Assets/Terms/TERMS-OF-USE.md";
    private const string EnglishAsset = "avares://NutManager.Agent.Config/Assets/Terms/TERMS-OF-USE.en-US.md";

    /// <summary>
    /// The terms in the requested language.
    ///
    /// A missing resource yields an empty document rather than throwing: the page is reachable from
    /// About, and an operator who opens it deserves an empty page over a window that closes itself.
    /// </summary>
    public static IReadOnlyList<AgentTermsBlock> Read(UiLanguagePreference language)
    {
        try
        {
            var asset = language == UiLanguagePreference.EnUs ? EnglishAsset : PortugueseAsset;

            using var stream = AssetLoader.Open(new Uri(asset));
            using var reader = new StreamReader(stream);

            return Parse(reader.ReadToEnd());
        }
        catch (Exception)
        {
            return [];
        }
    }

    /// <summary>
    /// Markdown to blocks, handling exactly the constructs these two documents use.
    ///
    /// The HTML comments are repository maintenance notes - which file is canonical, what has to be
    /// regenerated, what is still pending. They are not part of the legal text and must not reach the
    /// operator, which is the same rule the RTF generator applies.
    /// </summary>
    internal static IReadOnlyList<AgentTermsBlock> Parse(string markdown)
    {
        ArgumentNullException.ThrowIfNull(markdown);

        var blocks = new List<AgentTermsBlock>();
        var inComment = false;

        foreach (var raw in markdown.Split('\n'))
        {
            var line = raw.Trim();

            if (inComment)
            {
                if (line.Contains("-->", StringComparison.Ordinal)) inComment = false;
                continue;
            }

            if (line.StartsWith("<!--", StringComparison.Ordinal))
            {
                if (!line.Contains("-->", StringComparison.Ordinal)) inComment = true;
                continue;
            }

            if (line.Length == 0) continue;

            // A rule is a visual separator in Markdown and a blank line here: the headings already
            // separate the sections, and a drawn line between every one of twenty of them is noise.
            if (line is "---" or "***" or "___") continue;

            if (line.StartsWith("## ", StringComparison.Ordinal))
            {
                blocks.Add(new AgentTermsBlock(AgentTermsBlockKind.Heading, Clean(line[3..])));
                continue;
            }

            if (line.StartsWith("# ", StringComparison.Ordinal))
            {
                blocks.Add(new AgentTermsBlock(AgentTermsBlockKind.Title, Clean(line[2..])));
                continue;
            }

            if (line.StartsWith("- ", StringComparison.Ordinal))
            {
                blocks.Add(new AgentTermsBlock(AgentTermsBlockKind.Bullet, Clean(line[2..])));
                continue;
            }

            blocks.Add(new AgentTermsBlock(AgentTermsBlockKind.Paragraph, Clean(line)));
        }

        return blocks;
    }

    /// <summary>
    /// Inline markers removed, and nothing else.
    ///
    /// Emphasis and code ticks are presentation; the words between them are the term. Dropping the
    /// markers changes how a sentence looks and not what it says, which is the only latitude a legal
    /// document allows.
    /// </summary>
    private static string Clean(string text) =>
        Regex.Replace(text, @"\*\*(.+?)\*\*", "$1").Replace("`", string.Empty, StringComparison.Ordinal).Trim();
}
