<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\NutManager.Core\NutManager.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Diagnostics.EventLog" />
    <PackageReference Include="System.Management" />
    <PackageReference Include="System.ServiceProcess.ServiceController" />
    <PackageReference Include="SSH.NET" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="NutManager.Tests" />
  </ItemGroup>
</Project>
